# Generated by Django 2.0.1 on 2018-03-15 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('thumb_ups', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50, null=True)),
                ('star', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=50)),
                ('release_time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=30)),
                ('alternate_name', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField()),
                ('poster', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
