# Generated by Django 2.0.1 on 2018-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180315_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.CharField(max_length=500),
        ),
    ]
